---
output:
  word_document: default
  html_document: default
---
```{r capsAndEquations, include = FALSE}

procObsModelEqs <- read.csv("data/procModelEqns_EUL_hRicker.csv")
statModelEqs    <- read.csv("data/statModelEqns.csv")
# spModelEqs      <- read.csv("data/SSPMeqs.csv")

notationTableCap <- "Notation used in the specification of the SISCAL-EUL stock assessment model, along with a description of each variable, and possible fixed values."

procModelEqnTableCap  <- "Process and observation model equations for the SISCAL-EUL stock assessment model"

statModelEqnTableCap  <- "Statistical model prior and likelihood functions for the SISCAL-EUL stock assessment model. The function $\\textbf{1}(X)$ is the indicator function, taking value 1 when $X$ is true, and 0 when $X$ is false."

```
\clearpage

# TABLES

```{r SISCALnotation, echo = FALSE, message = FALSE, warnings = FALSE, eval = TRUE}
options(knitr.kable.NA = "")

notationTable <- tibble::tribble( 
    ~Symbol,           ~Value,           ~Description,
    "$T$",              "$53$",           "Total number of time steps 1965 - 2021",
    "$A$",              "$35$",           "Plus group age-class",
    "$L$",              "$32$",           "Number of length bins (4cm width)",
    "$t$",              "$1,2,\\dots,T$", "Time step",
    "$a$",              "$1,2,\\dots,A$", "Age-class index",
    "$l$",              "$2,6,\\dots,112$","Length-bin mid-points ($L = 32$ total length bins)",
    "$g$",              "$1,...,9$",      "Gear index as described in Table XX ($g=9$ only used in projections)", 
    "$x$",              "$1,2$",          "Sex index for males ($x=1$) and females ($x=2$)",
    "$B_{0}$",          NA,               "Unfished female spawning stock biomass",   
    "$h$",              NA,               "Ricker stock-recruitment steepness",
    "$R_{0}$",          NA,               "Unfished equilibrium age-1 recruitment",
    "$S_{a,x}$",        NA,               "Unfished equilibrium survivorship-at-age and sex",
    "$\\phi_{0}$",      NA,               "Unfished equilibrium spawning biomass per recruit",
    "$\\beta_1,\\beta_2$","$28.82, 10.55$","Beta prior parameters for steepness",
    "$\\omega_{t}$",    NA,               "Annual recruitment processs error log-deviations",
    "$\\sigma_{R}$",    "$1$",            "Standard error of $\\omega_{t}$ recruitment deviations",
    "$q_{g}$",          NA,               "Catchability coefficient for RV surveys ($g = 7,8,9$)",
    "$q_{t}$",          NA,               "Time-varying catchability coefficient for commercial CPUE index",
    "$M_{x,t}$",        NA,               "Time-varying natural mortality rate for males ($x = 1$) and females ($x=2$)",
    "$M_{0,x}$",        NA,               "Time-averaged natural mortality rate for males ($x = 1$) and females ($x=2$)",
    "$\\mu_M$",         "$0.14$",         "Natural mortality prior mean for males and females",
    "$\\sigma_M$",      "$0.05$",         "Natural mortality prior standard deviation for males and females",
    "$\\epsilon_{M,t}$",NA,               "Time-varying natural mortality random walk log-deviations",
    "$L_{\\infty,x}$",  "$68,72$",        "Asymptotic length (cm) for males ($x = 1$) and females ($x=2$)",
    "$\\sigma_{L,x}$",  "$0.08,0.11$",    "CV in length-at-age distribution",
    "$K_x$",            "$0.10,0.068$",   "von Bertalanffy growth constant for males and females",
    "$L_{1,x}$",        "$16.26,16.53$",  "Length-at-age 1 (same for males and females)",
    "$c_1,c_2$",        "$3.86e-6,3.22$", "Allometric length-weight transformation coefficients",
    "$l_{50},l_{95}$",  "$67,78$",        "Length-at-50\\% and -95\\% maturity",
    "$L_{a,x}$",        NA,               "Mean length-at-age (cm) for males and females",
    "$w_{a,x}$",        NA,               "Mean weight-at-age (cm) for males and females",
    "$m_l$",            NA,               "Proportion females mature-at-length",
    "$m_a$",            NA,               "Proportion females mature-at-age",
    "$s_{l,g}$",        NA,               "Mean selectivity-at-length $l$ for gear $g$",
    "$s_{a,x,g}$",      NA,               "Mean selectivity-at-age $a$ for gear $g$ and sex $x$",
    "$L_{50,g}^{A}$",   NA,               "Length-at-50\\% selectivity for ascending limb",
    "$L_{95,g}^{A}$",   NA,               "Length-at-95\\% selectivity for ascending limb",
    "$L_{50,g}^{D}$",   NA,               "Length-at-50\\% selectivity for descending limb",
    "$L_{95,g}^{D}$",   NA,               "Length-at-95\\% selectivity for descending limb",
    "$N_{a,x,t}$",      NA,               "Numbers-at-age $a$ for sex $x$ in year $t$",
    "$B_{t}$",          NA,               "Female spawning biomass in year $t$",
    "$C_{g,t}$",        NA,               "Observed total catch (biomass units) for gear $g$ in year $t$",
    "$C_{a,x,g,t}$",    NA,               "Expected catch-at-age (numbers) $a$ and sex $x$ by gear $g$ in year $t$",
    "$C'_{a,x,g,t}$",   NA,               "Expected catch-at-age (biomass units) $a$ and sex $x$ by gear $g$ in year $t$",
    "$B^{exp}_{t}$",    NA,               "Allocation weighted average exploitable biomass in year $t$",
    "$U_{g,t}$",        NA,               "Exploitation rate by gear $g$ in year $t$",
    "$U_{t}$",          NA,               "Total exploitation rate in year $t$",
    "$I_{g,t}$",        NA,               "Observed biomass/abundance index for gear $g \\in \\{7,8\\}$ in year $t$",
    "$\\hat{I}_{g,t}$", NA,               "Expected biomass/abundance index for gear $g \\in \\{7,8\\}$ in year $t$",
    "$\\tau_{g}$",      NA,               "Standard deviation of biomass index observation log-residuals",
    "$u_{l,x,g,t}$",      NA,             "Observed length composition data for sex $x$ in gear $g$ at time $t$",
    "$\\hat{u}_{l,x,g,t}$",NA,            "Expected length composition data for sex $x$ in gear $g$ at time $t$",
    "$\\hat{\\tau}^{len}_{x,g}$",NA,      "Conditional MLE of length composition sampling error, by sex and gear",
)


csasdown::csas_table( notationTable  , escape = FALSE,
                      booktabs = TRUE, font_size = 10,
                      format = kable_format,
                      linesep = "\\addlinespace[5pt]",
                      caption = notationTableCap,
                      align = c("c","c","l") ) |>
  kable_styling(  latex_options = c("hold_position", "scale_down"),
                  bootstrap_options = c("striped", "hover","scale_down"),
                  font_size = 10)

```

\clearpage



```{r procObsModelEqns, echo = FALSE, message = FALSE, warnings = FALSE, eval = TRUE }

colnames(procObsModelEqs) <- c("No.", "Equation")


kable( procObsModelEqs, 
        format = kable_format,
        escape = FALSE,
        linesep = "\\addlinespace[5pt]",
        booktabs = TRUE,
        caption = procModelEqnTableCap,
        longtable = TRUE,
        align = c("c","l")) |>
  kable_styling(latex_options = c("hold_position",
                                  "scale_down"),
                bootstrap_options = c("striped", "hover"),
                font_size = 10) |>
  kableExtra::pack_rows("Model Parameters", 1, 4 ) |>
  kableExtra::pack_rows("Growth and maturity", 5, 10 ) |>
  kableExtra::pack_rows("Selectivity", 11, 12 ) |>
  kableExtra::pack_rows("Unfished equilibrium states", 14, 17 ) |>
  kableExtra::pack_rows("Fishery removals", 18, 25 ) |>
  kableExtra::pack_rows("Spawning biomass, recruitment, and numbers-at-age", 26, 28 )
  

```

\clearpage

```{r statModelEqns, echo = FALSE, message = FALSE, warnings = FALSE, eval = TRUE }

colnames(statModelEqs) <- c("No.", "Equation")

kable( statModelEqs, escape = FALSE,
        booktabs = TRUE,
        format = kable_format,
        linesep = "\\addlinespace[5pt]",
        caption = statModelEqnTableCap,
        longtable = TRUE,
        align = c("c","l")) |>
  kable_styling(latex_options = c("hold_position","scale_down"),
                bootstrap_options = c("hover"),
                font_size = 10)  |>
  kableExtra::group_rows("Observation models for biomass index and composition data", 1, 2 ) |>
  kableExtra::group_rows("Biomass index likelihood", 3, 7 ) |>
  kableExtra::group_rows("Length composition likelihood", 8, 12 ) |>
  kableExtra::group_rows("Model priors", 13, 16 ) |>
  kableExtra::group_rows("Objective Function", 17, 17 )
  # kableExtra::group_rows("Observation models for biomass index and composition data", 1, 3 ) |>
  # kableExtra::group_rows("Biomass index likelihood", 4, 8 ) |>
  # kableExtra::group_rows("Length composition likelihood", 9, 13 ) |>
  # kableExtra::group_rows("Model priors", 14, 17 ) |>
  # kableExtra::group_rows("Objective Function", 18, 18 )

```

\clearpage
